#!/usr/bin/env python3
"""Splices the sync stats block generated by anilist-mal-sync into the README.

The sync command writes sync-stats.md containing a markdown block wrapped in
"<!-- SYNC-STATS:START -->" / "<!-- SYNC-STATS:END -->" comment markers. This
script replaces everything between those markers in README.md with the
generated block. If the file is missing (hard crash), a "sync failed" block is
written so the README never shows stale stats.
"""

import os
import re
import sys

STATS_FILE = "sync-stats.md"
README_FILE = "README.md"

START = "<!-- SYNC-STATS:START -->"
END = "<!-- SYNC-STATS:END -->"
FAILED_BLOCK = (
    START
    + "\n_Automatically updated by the anilist-mal-sync GitHub Actions workflow._\n\n"
    + "**Last sync: FAILED** - check the Actions run log for details.\n"
    + END
)


def main():
    if not os.path.exists(README_FILE):
        print(f"{README_FILE} not found, skipping stats update", file=sys.stderr)
        sys.exit(0)

    with open(README_FILE, encoding="utf-8") as f:
        readme = f.read()

    if os.path.exists(STATS_FILE):
        with open(STATS_FILE, encoding="utf-8") as f:
            block = f.read().strip()
        os.remove(STATS_FILE)
    else:
        block = FAILED_BLOCK

    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)

    if pattern.search(readme):
        new_readme = pattern.sub(block, readme)
    else:
        new_readme = readme.rstrip() + "\n\n## Sync Status\n\n" + block + "\n"

    if new_readme == readme:
        print("README stats already up to date, no changes")
        return

    with open(README_FILE, "w", encoding="utf-8") as f:
        f.write(new_readme)
    print("README stats updated")


if __name__ == "__main__":
    main()
